"""
Phase 3B - Centralized IDS Baseline

Trains one centralized MLP IDS using the complete Phase-1
training pool and evaluates ONLY on the locked test set.

Uses preprocessing artifacts generated by Phase 3A.

Research purpose:
    Centralized upper-bound/reference model.

Run:
    python scripts/phase3b_train_centralized_baseline.py

Optional:
    python scripts/phase3b_train_centralized_baseline.py \
        --epochs 5 \
        --batch-size 2048
"""

from __future__ import annotations

import argparse
import json
import logging
import random
from pathlib import Path

import joblib
import numpy as np
import pandas as pd

import torch
import torch.nn as nn

from sklearn.metrics import (
    accuracy_score,
    balanced_accuracy_score,
    classification_report,
    confusion_matrix,
    f1_score,
    precision_score,
    recall_score,
)


# ============================================================
# CONFIGURATION
# ============================================================

SEED = 42

PROJECT_ROOT = Path(__file__).resolve().parents[1]

DEFAULT_TRAIN_FILE = (
    PROJECT_ROOT
    / "data"
    / "processed"
    / "train.csv"
)

PREPROCESSING_DIR = (
    PROJECT_ROOT
    / "artifacts"
    / "preprocessing"
)

OUTPUT_DIR = (
    PROJECT_ROOT
    / "artifacts"
    / "centralized_baseline"
)

RESULTS_DIR = (
    PROJECT_ROOT
    / "results"
    / "centralized_baseline"
)

LABEL_COL = "Label"

DEFAULT_EPOCHS = 5
DEFAULT_BATCH_SIZE = 2048
DEFAULT_CHUNK_SIZE = 100_000
DEFAULT_LEARNING_RATE = 0.001
DEFAULT_WEIGHT_DECAY = 0.0001


# ============================================================
# LOGGING
# ============================================================

logging.basicConfig(
    level=logging.INFO,
    format="%(asctime)s | %(levelname)s | %(message)s"
)

logger = logging.getLogger("phase3b")


# ============================================================
# REPRODUCIBILITY
# ============================================================

def set_seed(seed: int):

    random.seed(seed)
    np.random.seed(seed)
    torch.manual_seed(seed)

    if torch.cuda.is_available():
        torch.cuda.manual_seed_all(seed)

    if hasattr(torch.backends, "cudnn"):
        torch.backends.cudnn.deterministic = True
        torch.backends.cudnn.benchmark = False


# ============================================================
# LABEL NORMALIZATION
# ============================================================

def normalize_label(label):

    label = str(label).strip()

    replacements = {

        "Web Attack � Brute Force":
            "Web Attack - Brute Force",

        "Web Attack � Sql Injection":
            "Web Attack - SQL Injection",

        "Web Attack � XSS":
            "Web Attack - XSS",

        "Web Attack – Brute Force":
            "Web Attack - Brute Force",

        "Web Attack – Sql Injection":
            "Web Attack - SQL Injection",

        "Web Attack – XSS":
            "Web Attack - XSS",
    }

    return replacements.get(label, label)


# ============================================================
# LOCKED TEST DISCOVERY
# ============================================================

def discover_locked_test_file():

    candidates = [

        PROJECT_ROOT
        / "data"
        / "processed"
        / "locked_test.csv",

        PROJECT_ROOT
        / "data"
        / "processed"
        / "test_locked.csv",

        PROJECT_ROOT
        / "data"
        / "processed"
        / "global_test.csv",

        PROJECT_ROOT
        / "data"
        / "processed"
        / "test.csv",
    ]

    for file in candidates:

        if file.exists():

            logger.info(
                "Locked test candidate found: %s",
                file
            )

            return file

    raise FileNotFoundError(
        "\nLocked test CSV could not be located.\n"
        "Specify it manually:\n\n"
        "python scripts/phase3b_train_centralized_baseline.py "
        "--test data/processed/YOUR_TEST_FILE.csv"
    )


# ============================================================
# LOAD PREPROCESSING ARTIFACTS
# ============================================================

def load_preprocessing():

    scaler_file = (
        PREPROCESSING_DIR
        / "scaler.joblib"
    )

    features_file = (
        PREPROCESSING_DIR
        / "feature_columns.json"
    )

    labels_file = (
        PREPROCESSING_DIR
        / "label_mapping.json"
    )

    required = [
        scaler_file,
        features_file,
        labels_file,
    ]

    for file in required:

        if not file.exists():

            raise FileNotFoundError(
                f"Missing Phase 3A artifact: {file}"
            )

    scaler = joblib.load(
        scaler_file
    )

    with open(
        features_file,
        "r",
        encoding="utf-8"
    ) as f:

        feature_columns = json.load(f)

    with open(
        labels_file,
        "r",
        encoding="utf-8"
    ) as f:

        label_mapping = json.load(f)

    return (
        scaler,
        feature_columns,
        label_mapping
    )


# ============================================================
# ACTIVE FEATURE DETECTION
# ============================================================

def detect_active_features(
    scaler,
    feature_columns
):

    """
    Remove zero-variance features.

    We still transform all original features using the
    Phase-3A scaler, then select active features.

    This avoids useless constant input neurons while
    preserving the frozen preprocessing pipeline.
    """

    variances = np.asarray(
        scaler.var_
    )

    active_indices = np.where(
        variances > 1e-12
    )[0]

    inactive_indices = np.where(
        variances <= 1e-12
    )[0]

    active_features = [
        feature_columns[i]
        for i in active_indices
    ]

    inactive_features = [
        feature_columns[i]
        for i in inactive_indices
    ]

    logger.info(
        "Original features : %d",
        len(feature_columns)
    )

    logger.info(
        "Active features   : %d",
        len(active_features)
    )

    logger.info(
        "Constant features : %d",
        len(inactive_features)
    )

    if inactive_features:

        logger.info(
            "Constant features removed from model input: %s",
            inactive_features
        )

    return (
        active_indices,
        active_features,
        inactive_features
    )


# ============================================================
# CLEAN + TRANSFORM FEATURES
# ============================================================

def transform_features(
    df,
    feature_columns,
    scaler,
    active_indices
):

    # Ensure consistent column names
    df.columns = [
        str(c).strip()
        for c in df.columns
    ]

    X = df[
        feature_columns
    ].copy()

    # Force numeric
    X = X.apply(
        pd.to_numeric,
        errors="coerce"
    )

    # Infinity -> NaN
    X = X.replace(
        [np.inf, -np.inf],
        np.nan
    )

    # Same rule as Phase 3A
    X = X.fillna(0.0)

    # Use frozen training scaler
    X_scaled = scaler.transform(X)

    # Remove constant features
    X_scaled = X_scaled[
        :,
        active_indices
    ]

    return X_scaled.astype(
        np.float32,
        copy=False
    )


# ============================================================
# ENCODE LABELS
# ============================================================

def encode_labels(
    series,
    label_mapping
):

    normalized = (
        series
        .astype(str)
        .map(normalize_label)
    )

    unknown = sorted(
        set(normalized.unique())
        - set(label_mapping.keys())
    )

    if unknown:

        raise ValueError(
            "Unknown labels detected: "
            f"{unknown}"
        )

    encoded = normalized.map(
        label_mapping
    )

    return encoded.to_numpy(
        dtype=np.int64
    )


# ============================================================
# COMPUTE TRAINING CLASS COUNTS
# ============================================================

def compute_class_counts(
    train_file,
    label_mapping,
    chunk_size
):

    counts = np.zeros(
        len(label_mapping),
        dtype=np.int64
    )

    logger.info(
        "Computing class counts from training data..."
    )

    for chunk_number, chunk in enumerate(
        pd.read_csv(
            train_file,
            usecols=[LABEL_COL],
            chunksize=chunk_size
        ),
        start=1
    ):

        y = encode_labels(
            chunk[LABEL_COL],
            label_mapping
        )

        batch_counts = np.bincount(
            y,
            minlength=len(label_mapping)
        )

        counts += batch_counts

        logger.info(
            "Class-count chunk %d processed.",
            chunk_number
        )

    return counts


# ============================================================
# CLASS WEIGHTS
# ============================================================

def calculate_class_weights(
    counts
):

    """
    Moderated inverse-frequency weighting.

        weight_c = sqrt(max_count / class_count)

    Extreme weights are capped at 20 to prevent tiny
    rare classes such as Heartbleed from destabilizing
    gradient updates.

    Finally normalize weights to mean 1.
    """

    safe_counts = np.maximum(
        counts.astype(np.float64),
        1.0
    )

    max_count = safe_counts.max()

    weights = np.sqrt(
        max_count / safe_counts
    )

    weights = np.minimum(
        weights,
        20.0
    )

    weights = (
        weights
        / weights.mean()
    )

    return weights.astype(
        np.float32
    )


# ============================================================
# MODEL
# ============================================================

class IDSMLP(nn.Module):

    def __init__(
        self,
        input_dim,
        num_classes
    ):

        super().__init__()

        self.network = nn.Sequential(

            nn.Linear(
                input_dim,
                256
            ),

            nn.LayerNorm(256),

            nn.ReLU(),

            nn.Dropout(0.20),

            nn.Linear(
                256,
                128
            ),

            nn.LayerNorm(128),

            nn.ReLU(),

            nn.Dropout(0.20),

            nn.Linear(
                128,
                64
            ),

            nn.LayerNorm(64),

            nn.ReLU(),

            nn.Dropout(0.10),

            nn.Linear(
                64,
                num_classes
            )
        )

    def forward(self, x):

        return self.network(x)


# ============================================================
# TRAIN ONE EPOCH
# ============================================================

def train_one_epoch(
    model,
    train_file,
    scaler,
    feature_columns,
    active_indices,
    label_mapping,
    criterion,
    optimizer,
    device,
    batch_size,
    chunk_size,
    epoch,
    seed
):

    model.train()

    running_loss = 0.0
    total_correct = 0
    total_samples = 0

    rng = np.random.default_rng(
        seed + epoch
    )

    for chunk_number, chunk in enumerate(
        pd.read_csv(
            train_file,
            chunksize=chunk_size
        ),
        start=1
    ):

        chunk.columns = [
            str(c).strip()
            for c in chunk.columns
        ]

        X = transform_features(
            chunk,
            feature_columns,
            scaler,
            active_indices
        )

        y = encode_labels(
            chunk[LABEL_COL],
            label_mapping
        )

        # Shuffle locally within each chunk
        indices = rng.permutation(
            len(X)
        )

        X = X[indices]
        y = y[indices]

        chunk_loss = 0.0
        chunk_correct = 0
        chunk_samples = 0

        for start in range(
            0,
            len(X),
            batch_size
        ):

            end = min(
                start + batch_size,
                len(X)
            )

            xb = torch.from_numpy(
                X[start:end]
            ).to(device)

            yb = torch.from_numpy(
                y[start:end]
            ).to(device)

            optimizer.zero_grad(
                set_to_none=True
            )

            logits = model(xb)

            loss = criterion(
                logits,
                yb
            )

            loss.backward()

            torch.nn.utils.clip_grad_norm_(
                model.parameters(),
                max_norm=5.0
            )

            optimizer.step()

            batch_n = len(yb)

            running_loss += (
                loss.item()
                * batch_n
            )

            chunk_loss += (
                loss.item()
                * batch_n
            )

            predicted = logits.argmax(
                dim=1
            )

            correct = (
                predicted == yb
            ).sum().item()

            total_correct += correct
            chunk_correct += correct

            total_samples += batch_n
            chunk_samples += batch_n

        logger.info(
            "Epoch %d | chunk %d | "
            "loss=%.6f | accuracy=%.4f",
            epoch,
            chunk_number,
            chunk_loss / max(chunk_samples, 1),
            chunk_correct / max(chunk_samples, 1)
        )

    epoch_loss = (
        running_loss
        / max(total_samples, 1)
    )

    epoch_accuracy = (
        total_correct
        / max(total_samples, 1)
    )

    return (
        epoch_loss,
        epoch_accuracy
    )


# ============================================================
# EVALUATION
# ============================================================

def evaluate(
    model,
    test_file,
    scaler,
    feature_columns,
    active_indices,
    label_mapping,
    device,
    batch_size,
    chunk_size
):

    model.eval()

    all_true = []
    all_pred = []

    logger.info(
        "Evaluating FINAL model on locked test set..."
    )

    with torch.no_grad():

        for chunk_number, chunk in enumerate(
            pd.read_csv(
                test_file,
                chunksize=chunk_size
            ),
            start=1
        ):

            chunk.columns = [
                str(c).strip()
                for c in chunk.columns
            ]

            X = transform_features(
                chunk,
                feature_columns,
                scaler,
                active_indices
            )

            y = encode_labels(
                chunk[LABEL_COL],
                label_mapping
            )

            predictions = []

            for start in range(
                0,
                len(X),
                batch_size
            ):

                end = min(
                    start + batch_size,
                    len(X)
                )

                xb = torch.from_numpy(
                    X[start:end]
                ).to(device)

                logits = model(xb)

                pred = logits.argmax(
                    dim=1
                )

                predictions.append(
                    pred
                    .cpu()
                    .numpy()
                )

            predictions = np.concatenate(
                predictions
            )

            all_true.append(y)

            all_pred.append(
                predictions
            )

            logger.info(
                "Locked-test chunk %d evaluated | rows=%d",
                chunk_number,
                len(chunk)
            )

    y_true = np.concatenate(
        all_true
    )

    y_pred = np.concatenate(
        all_pred
    )

    return (
        y_true,
        y_pred
    )


# ============================================================
# METRICS
# ============================================================

def calculate_metrics(
    y_true,
    y_pred,
    label_mapping
):

    inverse_mapping = {
        index: label
        for label, index
        in label_mapping.items()
    }

    class_ids = list(
        range(len(label_mapping))
    )

    target_names = [
        inverse_mapping[i]
        for i in class_ids
    ]

    overall = {

        "accuracy":
            float(
                accuracy_score(
                    y_true,
                    y_pred
                )
            ),

        "balanced_accuracy":
            float(
                balanced_accuracy_score(
                    y_true,
                    y_pred
                )
            ),

        "macro_precision":
            float(
                precision_score(
                    y_true,
                    y_pred,
                    average="macro",
                    zero_division=0
                )
            ),

        "macro_recall":
            float(
                recall_score(
                    y_true,
                    y_pred,
                    average="macro",
                    zero_division=0
                )
            ),

        "macro_f1":
            float(
                f1_score(
                    y_true,
                    y_pred,
                    average="macro",
                    zero_division=0
                )
            ),

        "weighted_f1":
            float(
                f1_score(
                    y_true,
                    y_pred,
                    average="weighted",
                    zero_division=0
                )
            ),

        "test_samples":
            int(len(y_true))
    }

    report = classification_report(
        y_true,
        y_pred,
        labels=class_ids,
        target_names=target_names,
        output_dict=True,
        zero_division=0
    )

    cm = confusion_matrix(
        y_true,
        y_pred,
        labels=class_ids
    )

    return (
        overall,
        report,
        cm,
        target_names
    )


# ============================================================
# SAVE RESULTS
# ============================================================

def save_results(
    model,
    overall,
    report,
    cm,
    target_names,
    history,
    active_features,
    inactive_features,
    label_mapping,
    class_counts,
    class_weights,
    args,
    train_file,
    test_file
):

    OUTPUT_DIR.mkdir(
        parents=True,
        exist_ok=True
    )

    RESULTS_DIR.mkdir(
        parents=True,
        exist_ok=True
    )

    # --------------------------------------------------------
    # Model
    # --------------------------------------------------------

    model_file = (
        OUTPUT_DIR
        / "centralized_mlp.pt"
    )

    torch.save(
        {
            "model_state_dict":
                model.state_dict(),

            "input_dim":
                len(active_features),

            "num_classes":
                len(label_mapping),

            "active_features":
                active_features,

            "label_mapping":
                label_mapping,

            "architecture":
                "MLP-256-128-64",

            "normalization":
                "LayerNorm"
        },
        model_file
    )

    # --------------------------------------------------------
    # Active features
    # --------------------------------------------------------

    with open(
        OUTPUT_DIR
        / "active_feature_columns.json",
        "w",
        encoding="utf-8"
    ) as f:

        json.dump(
            active_features,
            f,
            indent=4
        )

    # --------------------------------------------------------
    # Overall metrics
    # --------------------------------------------------------

    with open(
        RESULTS_DIR
        / "overall_metrics.json",
        "w",
        encoding="utf-8"
    ) as f:

        json.dump(
            overall,
            f,
            indent=4
        )

    # --------------------------------------------------------
    # Per-class metrics
    # --------------------------------------------------------

    rows = []

    for label in target_names:

        metrics = report[label]

        rows.append({

            "class": label,

            "precision":
                metrics["precision"],

            "recall":
                metrics["recall"],

            "f1_score":
                metrics["f1-score"],

            "support":
                metrics["support"]
        })

    pd.DataFrame(
        rows
    ).to_csv(
        RESULTS_DIR
        / "per_class_metrics.csv",
        index=False
    )

    # --------------------------------------------------------
    # Confusion matrix
    # --------------------------------------------------------

    cm_df = pd.DataFrame(
        cm,
        index=[
            f"TRUE::{name}"
            for name in target_names
        ],
        columns=[
            f"PRED::{name}"
            for name in target_names
        ]
    )

    cm_df.to_csv(
        RESULTS_DIR
        / "confusion_matrix.csv"
    )

    # --------------------------------------------------------
    # Training history
    # --------------------------------------------------------

    pd.DataFrame(
        history
    ).to_csv(
        RESULTS_DIR
        / "training_history.csv",
        index=False
    )

    # --------------------------------------------------------
    # Manifest
    # --------------------------------------------------------

    manifest = {

        "phase": "3B",

        "experiment":
            "Centralized MLP IDS Baseline",

        "purpose":
            "Centralized upper-bound reference",

        "training_file":
            str(train_file),

        "locked_test_file":
            str(test_file),

        "features_before_constant_removal":
            len(active_features)
            + len(inactive_features),

        "active_features":
            len(active_features),

        "constant_features_removed":
            inactive_features,

        "classes":
            len(label_mapping),

        "epochs":
            args.epochs,

        "batch_size":
            args.batch_size,

        "chunk_size":
            args.chunk_size,

        "learning_rate":
            args.learning_rate,

        "weight_decay":
            args.weight_decay,

        "optimizer":
            "AdamW",

        "loss":
            "Weighted CrossEntropyLoss",

        "class_weight_method":
            "sqrt(max_class_count/class_count), cap=20, mean-normalized",

        "gradient_clipping":
            5.0,

        "architecture":
            [
                len(active_features),
                256,
                128,
                64,
                len(label_mapping)
            ],

        "hidden_normalization":
            "LayerNorm",

        "seed":
            SEED,

        "test_used_during_training":
            False,

        "locked_test_used_for":
            "final evaluation only",

        "class_counts":
            {
                label:
                    int(
                        class_counts[index]
                    )
                for label, index
                in label_mapping.items()
            },

        "class_weights":
            {
                label:
                    float(
                        class_weights[index]
                    )
                for label, index
                in label_mapping.items()
            },

        "final_metrics":
            overall
    }

    with open(
        RESULTS_DIR
        / "phase3b_manifest.json",
        "w",
        encoding="utf-8"
    ) as f:

        json.dump(
            manifest,
            f,
            indent=4
        )

    return model_file


# ============================================================
# MAIN
# ============================================================

def main():

    parser = argparse.ArgumentParser()

    parser.add_argument(
        "--train",
        default=str(DEFAULT_TRAIN_FILE)
    )

    parser.add_argument(
        "--test",
        default=None
    )

    parser.add_argument(
        "--epochs",
        type=int,
        default=DEFAULT_EPOCHS
    )

    parser.add_argument(
        "--batch-size",
        type=int,
        default=DEFAULT_BATCH_SIZE
    )

    parser.add_argument(
        "--chunk-size",
        type=int,
        default=DEFAULT_CHUNK_SIZE
    )

    parser.add_argument(
        "--learning-rate",
        type=float,
        default=DEFAULT_LEARNING_RATE
    )

    parser.add_argument(
        "--weight-decay",
        type=float,
        default=DEFAULT_WEIGHT_DECAY
    )

    args = parser.parse_args()

    set_seed(SEED)

    train_file = Path(
        args.train
    )

    if not train_file.is_absolute():

        train_file = (
            PROJECT_ROOT
            / train_file
        )

    if not train_file.exists():

        raise FileNotFoundError(
            f"Training file missing: {train_file}"
        )

    if args.test:

        test_file = Path(
            args.test
        )

        if not test_file.is_absolute():

            test_file = (
                PROJECT_ROOT
                / test_file
            )

    else:

        test_file = (
            discover_locked_test_file()
        )

    if train_file.resolve() == test_file.resolve():

        raise RuntimeError(
            "TRAINING FILE AND TEST FILE ARE THE SAME. "
            "Stopping to prevent leakage."
        )

    # --------------------------------------------------------
    # Device
    # --------------------------------------------------------

    device = torch.device(
        "cuda"
        if torch.cuda.is_available()
        else "cpu"
    )

    logger.info(
        "PyTorch device: %s",
        device
    )

    if torch.cuda.is_available():

        logger.info(
            "GPU: %s",
            torch.cuda.get_device_name(0)
        )

    # --------------------------------------------------------
    # Load Phase-3A artifacts
    # --------------------------------------------------------

    (
        scaler,
        feature_columns,
        label_mapping
    ) = load_preprocessing()

    (
        active_indices,
        active_features,
        inactive_features
    ) = detect_active_features(
        scaler,
        feature_columns
    )

    # --------------------------------------------------------
    # Class counts + weighting
    # --------------------------------------------------------

    class_counts = compute_class_counts(
        train_file,
        label_mapping,
        args.chunk_size
    )

    class_weights = calculate_class_weights(
        class_counts
    )

    logger.info(
        "Training class statistics:"
    )

    for label, index in label_mapping.items():

        logger.info(
            "%02d | %-35s | count=%d | weight=%.4f",
            index,
            label,
            class_counts[index],
            class_weights[index]
        )

    # --------------------------------------------------------
    # Model
    # --------------------------------------------------------

    model = IDSMLP(
        input_dim=len(active_features),
        num_classes=len(label_mapping)
    ).to(device)

    parameter_count = sum(
        p.numel()
        for p in model.parameters()
    )

    logger.info(
        "Model parameters: %d",
        parameter_count
    )

    weight_tensor = torch.tensor(
        class_weights,
        dtype=torch.float32,
        device=device
    )

    criterion = nn.CrossEntropyLoss(
        weight=weight_tensor
    )

    optimizer = torch.optim.AdamW(
        model.parameters(),
        lr=args.learning_rate,
        weight_decay=args.weight_decay
    )

    # --------------------------------------------------------
    # Training
    # --------------------------------------------------------

    history = []

    print("\n")
    print("=" * 80)
    print("CENTRALIZED BASELINE TRAINING")
    print("=" * 80)

    for epoch in range(
        1,
        args.epochs + 1
    ):

        loss, accuracy = train_one_epoch(
            model=model,
            train_file=train_file,
            scaler=scaler,
            feature_columns=feature_columns,
            active_indices=active_indices,
            label_mapping=label_mapping,
            criterion=criterion,
            optimizer=optimizer,
            device=device,
            batch_size=args.batch_size,
            chunk_size=args.chunk_size,
            epoch=epoch,
            seed=SEED
        )

        history.append({

            "epoch":
                epoch,

            "train_loss":
                loss,

            "train_accuracy":
                accuracy
        })

        logger.info(
            "EPOCH %d/%d COMPLETE | "
            "loss=%.6f | accuracy=%.6f",
            epoch,
            args.epochs,
            loss,
            accuracy
        )

    # --------------------------------------------------------
    # Locked-test evaluation
    # --------------------------------------------------------

    y_true, y_pred = evaluate(
        model=model,
        test_file=test_file,
        scaler=scaler,
        feature_columns=feature_columns,
        active_indices=active_indices,
        label_mapping=label_mapping,
        device=device,
        batch_size=args.batch_size,
        chunk_size=args.chunk_size
    )

    (
        overall,
        report,
        cm,
        target_names
    ) = calculate_metrics(
        y_true,
        y_pred,
        label_mapping
    )

    # --------------------------------------------------------
    # Save
    # --------------------------------------------------------

    model_file = save_results(
        model=model,
        overall=overall,
        report=report,
        cm=cm,
        target_names=target_names,
        history=history,
        active_features=active_features,
        inactive_features=inactive_features,
        label_mapping=label_mapping,
        class_counts=class_counts,
        class_weights=class_weights,
        args=args,
        train_file=train_file,
        test_file=test_file
    )

    # --------------------------------------------------------
    # Display results
    # --------------------------------------------------------

    print("\n")
    print("=" * 80)
    print("PHASE 3B COMPLETE — CENTRALIZED BASELINE")
    print("=" * 80)

    print(
        f"Device             : {device}"
    )

    print(
        f"Input features     : {len(active_features)}"
    )

    print(
        f"Classes            : {len(label_mapping)}"
    )

    print(
        f"Training epochs    : {args.epochs}"
    )

    print(
        f"Test samples       : {overall['test_samples']:,}"
    )

    print(
        f"Accuracy           : "
        f"{overall['accuracy']:.6f}"
    )

    print(
        f"Balanced Accuracy  : "
        f"{overall['balanced_accuracy']:.6f}"
    )

    print(
        f"Macro Precision    : "
        f"{overall['macro_precision']:.6f}"
    )

    print(
        f"Macro Recall       : "
        f"{overall['macro_recall']:.6f}"
    )

    print(
        f"Macro F1           : "
        f"{overall['macro_f1']:.6f}"
    )

    print(
        f"Weighted F1        : "
        f"{overall['weighted_f1']:.6f}"
    )

    print(
        f"\nModel              : {model_file}"
    )

    print(
        f"Results            : {RESULTS_DIR}"
    )

    print(
        "\nLocked test used during training: NO ✅"
    )

    print(
        "Locked test used for final evaluation only: YES ✅"
    )

    print("\n")
    print("-" * 80)
    print("PER-ATTACK TEST PERFORMANCE")
    print("-" * 80)

    for name in target_names:

        m = report[name]

        print(
            f"{name:35s} "
            f"P={m['precision']:.4f} "
            f"R={m['recall']:.4f} "
            f"F1={m['f1-score']:.4f} "
            f"N={int(m['support'])}"
        )

    logger.info(
        "Phase 3B complete."
    )


if __name__ == "__main__":
    main()